services:
  - type: web
    name: n8n-afiliados
    env: docker
    plan: starter # O 'free' si estás probando (ojo con la RAM)
    healthCheckPath: /healthz
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      # PERMITE QUE EL NODO 'CODE' USE PLAYWRIGHT
      - key: NODE_FUNCTION_ALLOW_EXTERNAL
        value: playwright,chromium-bidi
      # EVITA QUE SE BORREN TUS DATOS (OBLIGATORIO EN RENDER)
      # Genera una clave random aquí: https://randomkeygen.com/
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
