- key: N8N_BASIC_AUTH_ACTIVE
  value: "true"
- key: N8N_BASIC_AUTH_USER
  value: "samuel"
- key: N8N_BASIC_AUTH_PASSWORD
  value: "4455668822"
- key: N8N_WEBHOOK_URL
  value: "https://n8n-ml-affiliates-1.onrender.com"
- key: N8N_HOST
  value: "n8n-ml-affiliates-1.onrender.com"
- key: N8N_PROTOCOL
  value: "https"
- key: PORT
  value: "10000"
